;1KB = 1024
;1MB = 1024*1024

; --------------------------------------------------
; HTTP 파라미터
; --------------------------------------------------
[http]
maxRequestLineBytes = 4KB    ; 최대 request-line 길이 (바이트, CRLF 포함 권장)
maxHeaderLineBytes = 4KB     ; 단일 헤더 라인 최대 길이 (바이트, CRLF 포함)
maxHeaderCount = 100          ; 허용되는 최대 헤더 개수
maxHeaderTotalBytes = 8KB    ; 전체 헤더 섹션의 최대 크기 (request-line 제외, CRLFCRLF 포함)
maxBodyBytes = 10MB           ; 요청 바디의 최대 크기 (바이트)
maxTransactionsPerConnection =10 ; 단일 연결당 최대 트랜잭션 수 (0이면 무제한)
; --------------------------------------------------
; HTTP 타임아웃 (서버/클라이언트)
; --------------------------------------------------
[httpserver.timeout]
requestFirstByteTimeoutSec = 10s       ; 첫 요청 라인 첫 바이트까지 최대 대기(초)
requestHeaderTimeoutSec    = 30s     ; 첫 바이트 수신 -> 헤더 전체 완료까지(초) 
requestBodyIdleTimeoutSec  = 60s     ; 요청 바디 수신 중 idle 타임아웃(초) 
transactionTimeoutSec      = 60s    ; 요청 완료 -> 응답(헤더+바디) 완료까지(초)
keepAliveTimeoutSec        = 60s     ; 응답 완료 후 다음 요청 대기(keep-alive)(초)

[httpclient.timeout]
requestSendIdleTimeoutSec  = 30s      ; 요청 전송(write) 중 idle 타임아웃(초)
responseHeaderTimeoutSec   = 30s     ; TTFB: 요청 완료 -> 응답 헤더/첫 바이트까지(초)
responseBodyIdleTimeoutSec = 60s     ; 응답 바디 수신 중 idle 타임아웃(초)
overallTimeoutSec          = 0             ; 전체 왕복 상한(초). 0이면 미사용

; --------------------------------------------------
; WebSocket 타임아웃/파라미터
; --------------------------------------------------
[websocket]
enabled        = true                ; false=비활성, true=활성
maxMessageBytes    = 1MB      ; 재조립된 전체 메시지 상한(바이트)
maxFrameBytes      = 64KB       ; 단일 프레임 상한(바이트)
maxMissingPongCount = 1      ; 허용되는 연속 미응답 pong 횟수

[websocket.timeout]
closeTimeoutSec  = 10s      ; close 프레임에 대한 응답 close 대기(초)
idleTimeoutSec   = 600s      ; 아무 프레임도 오가지 않는 idle 타임아웃(초)
pongTimeoutSec   = 10s      ; ping 이후 pong 대기(초)

; Subprotocol 설정 
[websocket.subprotocol]
policy  = optional                ; OPTIONAL| REQUIRED     
serverPreference = true         ; 서버 우선 선택 true| false             
onUnsupported    = ignore     ; 지원 안 되면 거절 reject | ignore  
;names= chat,echo         

; --------------------------------------------------
; 네트워크/포트 설정
; --------------------------------------------------
[net]
maxConnections=16      ; 
port           =12345        ; 일반 HTTP 포트 (>0 이면 enable)     
ssl.port       =0                ; HTTPS 포트 (>0 이면 enable)
ssl.certFile   = server.crt     ; 서버 인증서 파일 경로  
ssl.keyFile    = server.key    ; 서버 개인키 파일 경로
       

; --------------------------------------------------
; 로그 설정
; --------------------------------------------------
[log]
debugOut   = true       ; 디버그 출력 true|false               
consoleOut = false       ; 콘솔(stdout)에 로그 true|false              

; --------------------------------------------------
; 서버 호스트 정책
; --------------------------------------------------

[host.policy]
primaryHost   = example.com    ; 주 호스트명
allowAnyHost  = false                ; true 이면 Host 헤더 상관없이 허용(프록시/테스트용) 
aliasHosts = www.example.com , api.example.com
                